#!/usr/bin/zsh



app_folder=$(basename $PWD)

param=$1

function _change_dir_to_app_folder() {
	if [[ ! -z $APP_FOLDER ]]; then
	    cd $APP_FOLDER
	else
		export APP_FOLDER=$app_folder
		cd $APP_FOLDER
		echo $APP_FOLDER
	fi
}

if [[ "$param" == "live" ]]; then

	_change_dir_to_app_folder
	python manage.py livereload
	
elif [[ "$param" == "ipy" ]]; then

	_change_dir_to_app_folder
	python manage.py shell_plus

elif [[ "$param" == "dev" ]]; then

	_change_dir_to_app_folder
	python manage.py runserver 0:5555

elif [[ "$param" == "dev+" ]]; then

	_change_dir_to_app_folder
	python manage.py runserver_plus 0:5555

elif [[ "$param" == "freeze" ]]; then
	pip freeze > requirements.txt



elif [[ "$param" == "test" ]]; then
	_change_dir_to_app_folder
	w=$2
	if [[ -z $w ]]; then
		# durations is to print all durations for every called func
		pytest -vv -x -rP --color=yes --durations=0
	else
		pytest -vv -x -rP -n $w --color=yes --durations=0
	fi

else
	echo "you must provide args"
	echo "like"
	echo -e "\t ./manager.sh live (for livereload server)"
	echo -e "\t ./manager.sh dev (for django dev server)"
fi