# Generated by Django 3.0.1 on 2021-12-22 22:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['name', 'age'],
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='authtoken',
            managers=[
                ('tokens', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterModelTable(
            name='authtoken',
            table='"auth_tokens_table"',
        ),
    ]
