# Generated by Django 3.0.1 on 2021-12-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211222_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
