# Generated by Django 3.0.1 on 2021-12-22 23:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211222_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': '"auth_tokens_table"',
            },
            managers=[
                ('tokens', django.db.models.manager.Manager()),
            ],
        ),
    ]
