# Generated by Django 3.0.1 on 2021-12-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_reporter_full_name2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='full_name2',
            new_name='age',
        ),
    ]
