# Generated by Django 3.0.1 on 2021-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20211221_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='full_name2',
            field=models.CharField(default='andrew', max_length=70),
            preserve_default=False,
        ),
    ]
