# Generated by Django 3.0.1 on 2021-12-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_reporter_full_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='age',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='full_name2',
        ),
    ]
